#!/bin/sh

cd /tmp
rm *_DNBCTR.tar.gz

find /data4/BRF/CTR_LOGS/bot-sftp-sharepoint-service-ver1-CTR__EANKRAG__20230308??????/CTR_Files/????????/ -name "*0800+0800-0815+0800_*DBPET0993_UITMSHAHALAM*CUCP*.gpb.gz" -type f -print | xargs tar -czf /tmp/0800+0800-0815+0800_DBPET0993_CUCP_DNBCTR.tar.gz
find /data4/BRF/CTR_LOGS/bot-sftp-sharepoint-service-ver1-CTR__EANKRAG__20230308??????/CTR_Files/????????/ -name "*0800+0800-0815+0800_*DBPET1212_DAMANSARAINTAN*CUCP*.gpb.gz" -type f -print | xargs tar -czf /tmp/0800+0800-0815+0800_DBPET1212_CUCP_DNBCTR.tar.gz
find /data4/BRF/CTR_LOGS/bot-sftp-sharepoint-service-ver1-CTR__EANKRAG__20230308??????/CTR_Files/????????/ -name "*0800+0800-0815+0800_*DBPET0766_MENARACHOYFOOKONN*CUCP*.gpb.gz" -type f -print | xargs tar -czf /tmp/0800+0800-0815+0800_DBPET0766_CUCP_DNBCTR.tar.gz
find /data4/BRF/CTR_LOGS/bot-sftp-sharepoint-service-ver1-CTR__EANKRAG__20230308??????/CTR_Files/????????/ -name "*0800+0800-0815+0800_*DBSEP1414_JLNSIERRABNDR16*CUCP*.gpb.gz" -type f -print | xargs tar -czf /tmp/0800+0800-0815+0800_DBSEP1414_CUCP_DNBCTR.tar.gz
find /data4/BRF/CTR_LOGS/bot-sftp-sharepoint-service-ver1-CTR__EANKRAG__20230308??????/CTR_Files/????????/ -name "*0800+0800-0815+0800_*DBSEP1435_SYABASBKTPUCHONG2*CUCP*.gpb.gz" -type f -print | xargs tar -czf /tmp/0800+0800-0815+0800_DBSEP1435_CUCP_DNBCTR.tar.gz
find /data4/BRF/CTR_LOGS/bot-sftp-sharepoint-service-ver1-CTR__EANKRAG__20230308??????/CTR_Files/????????/ -name "*0800+0800-0815+0800_*DBPET0915_TABUNGHAJI*CUCP*.gpb.gz" -type f -print | xargs tar -czf /tmp/0800+0800-0815+0800_DBPET0915_CUCP_DNBCTR.tar.gz
find /data4/BRF/CTR_LOGS/bot-sftp-sharepoint-service-ver1-CTR__EANKRAG__20230308??????/CTR_Files/????????/ -name "*0800+0800-0815+0800_*DWPPJ0872_APTPRIMAPRESINT11*CUCP*.gpb.gz" -type f -print | xargs tar -czf /tmp/0800+0800-0815+0800_DWPPJ0872_CUCP_DNBCTR.tar.gz
find /data4/BRF/CTR_LOGS/bot-sftp-sharepoint-service-ver1-CTR__EANKRAG__20230308??????/CTR_Files/????????/ -name "*0800+0800-0815+0800_*DBSEP1434_JLNDALPUTAMA*CUCP*.gpb.gz" -type f -print | xargs tar -czf /tmp/0800+0800-0815+0800_DBSEP1434_CUCP_DNBCTR.tar.gz

#cp source path /tmp/foldername/

#tar -czf /tmp/CUCP_DNBCTR.tar.gz /tmp/foldername


#UPLOAD TO SHAREPOINT
cd /home/hawkuser/RAN/CTR_Files_bot-sftp-sharepoint-service-ver1
java -jar bot-sftp-sharepoint-service-ver1-0.0.1-SNAPSHOT.jar "bot-sftp-sharepoint-service-ver1-MANUALCTR_" --spring.config.location=./MANUAL_CTR_CONFIG/

cd /tmp
rm *_DNBCTR.tar.gz
